spring.datasource:
  url: jdbc:mysql://localhost/BazarPC?createDatabaseIfNotExist=true
  username: root
  password: 1234
  driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8080

# Logging for debugging
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework: INFO
  file:
    name: logs/myapp.log
