spring.datasource:
  url: jdbc:mysql://localhost/BazarPC?createDatabaseIfNotExist=true
  username: root
  password: 1234
  driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080